version: '3.4'

services:
    bridgeapi:
        build: ./Bridge-API/
        ports:
            - 3000:3000
        expose:
            - '3000'
        restart: "on-failure"
        depends_on: 
            - gptapi
            - translatorapi
    gptapi:
        build: ./GPT2-API/
        ports:
            - 3001:3001
        expose:
            - '3001'
        restart: "on-failure"
    translatorapi:
        build: ./Translator-API/
        ports:
            - 3002:3002
        expose:
            - '3002'
        restart: "on-failure"